In [ ]:
import os
import numpy as np
from sklearn.cluster import KMeans
from langchain_nebius.embeddings import NebiusEmbeddings

# ==========================================
# STEP 1: Setup and Mock Data
# ==========================================
# Imagine these are the chunks you extracted using Docling's Hybrid Chunker
docling_chunks = [
    "The basic subscription costs $10 per month and includes 500 API calls.",
    "Premium tier is $50 per month with unlimited API calls and priority support.",
    "To reset your password, navigate to the settings menu and click 'Security'.",
    "If you forget your password, the recovery email will be sent within 5 minutes.",
    "Enterprise plans require a custom contract and include dedicated account managers.",
]

# We use Chroma's default embedding function (all-MiniLM-L6-v2) for demonstration
# In production, you might use OpenAIEmbeddingFunction or Cohere
emb_fn = NebiusEmbeddings(api_key=os.environ.get("EMBEDDING_API_KEY"))
raw_embeddings = emb_fn.embed_documents(docling_chunks)
embeddings_array = np.array(raw_embeddings)

# ==========================================
# STEP 2: Spherical K-Means Clustering
# ==========================================
# CRITICAL: Normalize embeddings so K-Means (Euclidean) acts like Cosine Similarity
norms = np.linalg.norm(embeddings_array, axis=1, keepdims=True)
normalized_embeddings = embeddings_array / norms

# Define how many buckets (clusters) we want.
# For 5 chunks, 2 clusters makes sense. For 10,000 chunks, you might want 500.
num_clusters = 3

# Initialize and fit the K-Means algorithm
kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init="auto")
kmeans.fit(normalized_embeddings)

# Extract the assigned bucket IDs for each chunk
# This will be an array like: [0, 0, 1, 1, 0]
cluster_assignments = kmeans.labels_
print(cluster_assignments)

[2 0 1 1 0]

:

In [5]:
## FOR IMPORTING MODULES FROM /app

import sys
import os

# Get the directory where the notebook is running
project_root = os.path.abspath(
    os.path.join(os.getcwd(), "..")
)  # Adjust '..' based on depth

if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [6]:
from typing import Any

from ragas import experiment, Dataset
from ragas.backends import LocalCSVBackend
from pydantic import BaseModel


class DatasetModelSingleTurn(BaseModel):
    id: int
    query: str
    expected_answer: str
    metadata: dict[str, Any] | None = None


backend = LocalCSVBackend(root_dir="./dataset")
dataset_1 = Dataset(
    name="dataset_1", backend=backend, data_model=DatasetModelSingleTurn
)

data = [
    DatasetModelSingleTurn(
        id=1, query="What is the capital of France?", expected_answer="Paris"
    ),
    DatasetModelSingleTurn(
        id=2,
        query="What is the chemical symbol for gold?",
        expected_answer="Au",
        metadata={"category": "science", "difficulty": "easy"},
    ),
    DatasetModelSingleTurn(
        id=3,
        query="Who wrote 'To Kill a Mockingbird'?",
        expected_answer="Harper Lee",
        metadata=None,  # Explicitly setting to None, though it's the default
    ),
    DatasetModelSingleTurn(
        id=4,
        query="What is the largest planet in our solar system?",
        expected_answer="Jupiter",
        metadata={"category": "astronomy"},
    ),
    DatasetModelSingleTurn(
        id=5,
        query="In what year did the Apollo 11 moon landing occur?",
        expected_answer="1969",
    ),
    DatasetModelSingleTurn(
        id=6,
        query="What is the speed of light in a vacuum?",
        expected_answer="Approximately 299,792 kilometers per second",
        metadata={"category": "physics", "exact_value": 299792458},
    ),
]

for d in data:
    dataset_1.append(d)

dataset_1.to_pandas()

,id,query,expected_answer,metadata
0,1,What is the capital of France?,Paris,None
1,2,What is the chemical symbol for gold?,Au,"{'category': 'science', 'difficulty': 'easy'}"
2,3,Who wrote 'To Kill a Mockingbird'?,Harper Lee,None
3,4,What is the largest planet in our solar system?,Jupiter,{'category': 'astronomy'}
4,5,In what year did the Apollo 11 moon landing oc...,1969,None
5,6,What is the speed of light in a vacuum?,"Approximately 299,792 kilometers per second","{'category': 'physics', 'exact_value': 299792458}"

In [7]:
# import asyncio

# from ragas import experiment, Dataset
# from ragas.backends import LocalCSVBackend
# from app.routes.dependencies.llm import get_chat_model_service
# from app.routes.dependencies.settings import get_app_settings
# from langchain_core.messages import HumanMessage

# app_settings = get_app_settings()
# chat_model_service = get_chat_model_service(app_settings)


# @experiment()
# async def experiment_model_prompt(
#     row: DatasetModelSingleTurn, model_name: str, temperature: float
# ):
#     model = chat_model_service.client
#     response = model.invoke([HumanMessage(content=row.query)]).content

#     return {
#         **row.model_dump(),
#         "response": response,
#         "experiment_name": f"{model_name}_temp_{temperature}",
#         "model_name": model_name,
#         "temperature": temperature,
#     }


# results_1 = await experiment_model_prompt.arun(
#     dataset=dataset_1, model_name="gpt40", temperature=1.0
# )
# results_1.to_pandas()

Running experiment:   0%|          | 0/6 [00:00<?, ?it/s]

[2026-03-06 09:29:42,662][INFO] factory:client:46             Selected model: ChatNebius
[2026-03-06 09:29:45,837][INFO] _client:_send_single_request:1025             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:29:47,631][INFO] _client:_send_single_request:1025             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:29:49,925][INFO] _client:_send_single_request:1025             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:29:51,868][INFO] _client:_send_single_request:1025             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:29:53,395][INFO] _client:_send_single_request:1025             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:29:54,694][INFO] _client:_send_single_request:1025             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Running experiment: 100%|██████████| 6/6 [00:12<00:00,  2.16s/it]

,id,query,expected_answer,metadata,response,experiment_name,model_name,temperature
0,5,In what year did the Apollo 11 moon landing oc...,1969,None,The Apollo 11 moon landing **occurred in 1969*...,gpt40_temp_1.0,gpt40,1.0
1,4,What is the largest planet in our solar system?,Jupiter,{'category': 'astronomy'},That’s easy — the largest planet in our solar ...,gpt40_temp_1.0,gpt40,1.0
2,6,What is the speed of light in a vacuum?,"Approximately 299,792 kilometers per second","{'category': 'physics', 'exact_value': 299792458}",The speed of light in a **vacuum** is a fundam...,gpt40_temp_1.0,gpt40,1.0
3,3,Who wrote 'To Kill a Mockingbird'?,Harper Lee,None,**Harper Lee** is the author of ***To Kill a M...,gpt40_temp_1.0,gpt40,1.0
4,1,What is the capital of France?,Paris,None,The capital of France is **Paris**. Known for ...,gpt40_temp_1.0,gpt40,1.0
5,2,What is the chemical symbol for gold?,Au,"{'category': 'science', 'difficulty': 'easy'}",The chemical symbol for **gold** is **Au**. \n,gpt40_temp_1.0,gpt40,1.0

In [10]:
import os
import pandas as pd
from dotenv import load_dotenv

# LangChain Imports
from langchain_community.document_loaders import DirectoryLoader
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

# Ragas Imports
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset.graph import KnowledgeGraph, Node, NodeType
from ragas.testset.transforms import (
    HeadlinesExtractor,
    HeadlineSplitter,
    KeyphrasesExtractor,
    apply_transforms,
)
from ragas.testset.persona import Persona
from ragas.testset.synthesizers.single_hop.specific import (
    SingleHopSpecificQuerySynthesizer,
)
from ragas.testset import TestsetGenerator

from app.routes.dependencies.embedding import get_embedding

app_settings = get_app_settings()
chat_model_service = get_chat_model_service(app_settings)
embedding_service = get_embedding(app_settings)


def generate_golden_dataset():
    # 1. Setup Environment & Models
    # Using a high-capability model for generation ensures high-quality golden answers
    load_dotenv()
    os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

    eval_llm = chat_model_service.client
    eval_embeddings = embedding_service.client

    # Wrap models for Ragas compatibility
    generator_llm = LangchainLLMWrapper(eval_llm)
    generator_embeddings = LangchainEmbeddingsWrapper(eval_embeddings)

    # 2. Load Source Documents
    print("Loading documents...")
    loader = DirectoryLoader(
        "./data", glob="**/*.pdf", use_multithreading=True
    )  # Adjust path and glob as needed
    docs = loader.load()

    # 3. Create the Base Knowledge Graph
    print("Initializing Knowledge Graph...")
    kg = KnowledgeGraph()
    for doc in docs:
        kg.nodes.append(
            Node(
                type=NodeType.DOCUMENT,
                properties={
                    "page_content": doc.page_content,
                    "document_metadata": doc.metadata,
                },
            )
        )

    # 4. Enrich the Knowledge Graph via Transforms
    # This extracts semantic properties so the synthesizers can build realistic queries
    print("Applying Knowledge Graph Transformations...")
    transforms = [
        HeadlinesExtractor(llm=generator_llm, max_num=10),
        HeadlineSplitter(max_tokens=1500),
        KeyphrasesExtractor(llm=generator_llm),
    ]
    apply_transforms(kg, transforms=transforms)

    # PROD TIP: Save the KG state. If generation fails or you want to generate
    # more questions later, you won't have to pay to re-compute the graph.
    kg.save("enriched_knowledge_graph.json")
    print("Knowledge Graph saved locally.")

    # 5. Define Personas
    # Personas simulate different user behaviors to ensure dataset diversity
    personas = [
        Persona(
            name="Domain Expert",
            role_description="Asks highly technical, detailed questions seeking deep, granular understanding.",
        ),
        Persona(
            name="Novice User",
            role_description="Asks simple, high-level questions and needs broad, accessible explanations.",
        ),
    ]

    # 6. Configure Synthesizers & Query Distribution
    # Map the extracted graph properties (headlines, keyphrases) to specific query generators
    query_distribution = [
        (
            SingleHopSpecificQuerySynthesizer(
                llm=generator_llm, property_name="keyphrases"
            ),
            0.6,
        ),  # 60% based on key themes
        (
            SingleHopSpecificQuerySynthesizer(
                llm=generator_llm, property_name="headlines"
            ),
            0.4,
        ),  # 40% based on section headers
    ]

    # 7. Generate the Testset
    print("Generating Golden Dataset...")
    generator = TestsetGenerator(
        llm=generator_llm,
        embedding_model=generator_embeddings,
        knowledge_graph=kg,
        persona_list=personas,
    )

    # Generate the actual Q&A pairs
    testset = generator.generate(testset_size=50, query_distribution=query_distribution)

    # 8. Export Data
    df = testset.to_pandas()
    df.to_csv("golden_dataset.csv", index=False)
    print("Golden dataset successfully generated and saved to 'golden_dataset.csv'!")

    return df


if __name__ == "__main__":
    golden_df = generate_golden_dataset()
    print(golden_df.head())

C:\Users\kairu\AppData\Local\Temp\ipykernel_26700\660659701.py:42: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(eval_llm)
C:\Users\kairu\AppData\Local\Temp\ipykernel_26700\660659701.py:43: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(eval_embeddings)

Loading documents...

[2026-03-06 09:33:08,930][INFO] __init__:<module>:13             pikepdf C++ to Python logger bridge initialized

Warning: No languages specified, defaulting to English.
Initializing Knowledge Graph...
Applying Knowledge Graph Transformations...

Applying HeadlinesExtractor:   0%|          | 0/1 [00:00<?, ?it/s][2026-03-06 09:33:34,517][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:40,036][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying HeadlinesExtractor: 100%|██████████| 1/1 [00:15<00:00, 15.57s/it]
Applying HeadlineSplitter: 100%|██████████| 1/1 [00:02<00:00,  2.77s/it]
Applying KeyphrasesExtractor:   0%|          | 0/48 [00:00<?, ?it/s][2026-03-06 09:33:46,017][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:46,082][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:   2%|▏         | 1/48 [00:03<02:38,  3.36s/it][2026-03-06 09:33:47,247][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:47,248][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:47,249][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:   4%|▍         | 2/48 [00:06<02:33,  3.34s/it][2026-03-06 09:33:50,578][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:50,580][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:50,582][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:50,583][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:50,585][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:50,587][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:50,589][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:  10%|█         | 5/48 [00:15<02:10,  3.03s/it][2026-03-06 09:33:59,289][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:59,290][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:59,291][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:59,292][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:59,293][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:59,294][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:59,295][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:33:59,296][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:  25%|██▌       | 12/48 [00:24<01:03,  1.78s/it][2026-03-06 09:34:10,404][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:10,420][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:  42%|████▏     | 20/48 [00:27<00:29,  1.06s/it][2026-03-06 09:34:11,622][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,623][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,624][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,625][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,626][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,627][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,628][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,632][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,633][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,634][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:11,635][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:  44%|████▍     | 21/48 [00:38<00:52,  1.94s/it][2026-03-06 09:34:22,742][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:22,744][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:22,745][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:22,746][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:  65%|██████▍   | 31/48 [00:45<00:20,  1.23s/it][2026-03-06 09:34:31,650][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:31,675][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:31,689][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:31,693][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:31,695][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:31,696][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:31,697][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor:  77%|███████▋  | 37/48 [00:48<00:11,  1.02s/it][2026-03-06 09:34:32,819][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:32,820][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:32,821][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:32,822][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:32,823][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Applying KeyphrasesExtractor: 100%|██████████| 48/48 [01:00<00:00,  1.27s/it]

Knowledge Graph saved locally.
Generating Golden Dataset...

Generating Scenarios:   0%|          | 0/2 [00:00<?, ?it/s][2026-03-06 09:34:47,158][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:49,547][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Scenarios:  50%|█████     | 1/2 [00:05<00:05,  5.88s/it][2026-03-06 09:34:50,701][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:53,424][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:56,103][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:34:58,963][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:01,511][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:04,261][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:07,151][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:10,232][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:13,070][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:15,763][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:18,591][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:21,774][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:24,891][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:28,156][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:31,369][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:34,191][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:37,043][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:39,819][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:42,707][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:45,872][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:48,441][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:51,496][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:54,940][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:35:58,147][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:00,987][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:03,873][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:07,250][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:10,458][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:13,787][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Scenarios: 100%|██████████| 2/2 [01:30<00:00, 45.13s/it]
Generating Samples:   0%|          | 0/50 [00:00<?, ?it/s][2026-03-06 09:36:17,564][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:   2%|▏         | 1/50 [00:03<03:01,  3.71s/it][2026-03-06 09:36:18,818][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:   4%|▍         | 2/50 [00:05<01:51,  2.32s/it][2026-03-06 09:36:20,154][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:20,157][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:20,161][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:   6%|▌         | 3/50 [00:08<02:19,  2.97s/it][2026-03-06 09:36:23,897][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:23,899][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:23,901][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:23,902][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:23,904][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:23,905][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  12%|█▏        | 6/50 [00:15<01:52,  2.55s/it][2026-03-06 09:36:30,904][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:30,910][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:30,911][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:30,912][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:30,914][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  24%|██▍       | 12/50 [00:20<00:52,  1.37s/it][2026-03-06 09:36:35,416][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:35,418][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:35,420][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:35,422][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:35,424][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:35,426][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  32%|███▏      | 16/50 [00:21<00:32,  1.05it/s][2026-03-06 09:36:42,214][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.486676 seconds
[2026-03-06 09:36:42,215][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.458944 seconds
[2026-03-06 09:36:42,216][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.471524 seconds
[2026-03-06 09:36:42,216][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.462058 seconds
[2026-03-06 09:36:42,217][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.442344 seconds
[2026-03-06 09:36:42,218][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.389954 seconds
[2026-03-06 09:36:42,218][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.452260 seconds
[2026-03-06 09:36:42,219][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.380414 seconds
[2026-03-06 09:36:42,220][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.461277 seconds
[2026-03-06 09:36:42,220][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.472337 seconds
[2026-03-06 09:36:42,221][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.487517 seconds
[2026-03-06 09:36:42,221][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.492241 seconds
[2026-03-06 09:36:42,222][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.471517 seconds
[2026-03-06 09:36:42,222][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.422052 seconds
[2026-03-06 09:36:42,223][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.469039 seconds
[2026-03-06 09:36:42,223][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.415363 seconds
[2026-03-06 09:36:42,224][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.417148 seconds
[2026-03-06 09:36:42,225][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.379963 seconds
[2026-03-06 09:36:42,226][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.480041 seconds
[2026-03-06 09:36:42,226][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.383413 seconds
[2026-03-06 09:36:42,227][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.463854 seconds
[2026-03-06 09:36:42,227][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.458870 seconds
[2026-03-06 09:36:42,228][INFO] _base_client:_sleep_for_retry:1690             Retrying request to /chat/completions in 0.411626 seconds
Generating Samples:  34%|███▍      | 17/50 [00:27<00:50,  1.53s/it][2026-03-06 09:36:42,230][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:42,231][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:42,233][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:36:42,234][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  44%|████▍     | 22/50 [00:31<00:35,  1.26s/it][2026-03-06 09:36:46,960][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  54%|█████▍    | 27/50 [00:34<00:21,  1.06it/s][2026-03-06 09:37:20,009][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  56%|█████▌    | 28/50 [01:06<01:53,  5.16s/it][2026-03-06 09:37:21,233][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:21,234][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  58%|█████▊    | 29/50 [01:08<01:38,  4.69s/it][2026-03-06 09:37:23,514][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:23,515][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:23,517][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:23,518][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  62%|██████▏   | 31/50 [01:12<01:14,  3.93s/it][2026-03-06 09:37:28,058][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:28,060][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:28,061][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  70%|███████   | 35/50 [01:15<00:35,  2.33s/it][2026-03-06 09:37:30,361][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:30,362][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:30,363][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:30,364][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  74%|███████▍  | 37/50 [01:16<00:24,  1.89s/it][2026-03-06 09:37:31,510][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:31,511][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:31,512][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:31,514][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:31,515][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples:  76%|███████▌  | 38/50 [01:19<00:25,  2.12s/it][2026-03-06 09:37:34,928][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:34,929][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:34,931][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2026-03-06 09:37:34,933][INFO] _client:_send_single_request:1740             HTTP Request: POST https://api.studio.nebius.ai/v1/chat/completions "HTTP/1.1 200 OK"
Generating Samples: 100%|██████████| 50/50 [01:31<00:00,  1.82s/it]

Golden dataset successfully generated and saved to 'golden_dataset.csv'!
                                          user_input  \
0  What is the Andromeda Galaxy and how far away ...
1                What's the Milky Way's name origin?
2                  What are some well-known galaxys?
3                 What is a supermassive black hole?
4                                        star counts

                                  reference_contexts  \
0  [3/2/26, 11:26 AM\n\nGalaxy - Wikipedia\n\nGal...
1  [Etymology\n\nThe word galaxy was borrowed via...
2  [Nomenclature\n\nMillions of galaxies have bee...
3  [Milky Way galaxy that contains the Solar Syst...
4  [sphere of the fixed stars."[29] Actual proof ...

                                           reference   persona_name  \
0  The Andromeda Galaxy is the nearest large neig...    Novice User
1  The word galaxy was borrowed from the Greek te...  Domain Expert
2  Well-known galaxies include the Andromeda Gala...    Novice User
3  Supermassive black holes are a common feature ...    Novice User
4  The first project to describe the shape of the...  Domain Expert

       query_style query_length                       synthesizer_name
0     POOR_GRAMMAR       MEDIUM  single_hop_specific_query_synthesizer
1     POOR_GRAMMAR        SHORT  single_hop_specific_query_synthesizer
2       MISSPELLED        SHORT  single_hop_specific_query_synthesizer
3     POOR_GRAMMAR        SHORT  single_hop_specific_query_synthesizer
4  WEB_SEARCH_LIKE        SHORT  single_hop_specific_query_synthesizer